package com.nexuzy.samvixo.ui.navigation

sealed class Screen(val route: String) {
    object Auth              : Screen("auth")
    object OnboardingName    : Screen("onboarding_name")
    object Chats             : Screen("chats")
    object ChatDetail        : Screen("chat_detail/{chatId}/{peerName}")
    object SecretChat        : Screen("secret_chat/{chatId}/{peerName}")
    object GroupChat         : Screen("group_chat/{chatId}/{peerName}")
    object Status            : Screen("status")
    object StatusCreate      : Screen("status_create")
    object Channels          : Screen("channels")
    object CreateChannel     : Screen("create_channel")
    object ChannelCreation   : Screen("channel_creation")
    object ChannelDetail     : Screen("channel_detail/{channelId}")
    object GroupCreation     : Screen("group_creation")
    object BroadcastCreation : Screen("broadcast_creation")
    object Broadcast         : Screen("broadcast")
    object AI                : Screen("ai")
    object AINotes           : Screen("ai_notes")
    object AIVault           : Screen("ai_vault")
    object Settings          : Screen("settings")
    object Account           : Screen("account")
    object Avatar            : Screen("avatar")
    object EditProfile       : Screen("edit_profile")
    object Profile           : Screen("profile")
    object ProfileSettings   : Screen("profile_settings")
    object UserProfileView   : Screen("user_profile/{uid}")
    object NotifSettings     : Screen("notif_settings")
    object StorageData       : Screen("storage_data")
    object AppLanguage       : Screen("app_language")
    object AppLocker         : Screen("app_locker")
    object EmergencyMesh     : Screen("emergency_mesh")
    object InviteFriend      : Screen("invite_friend")
    object WallpaperPicker   : Screen("wallpaper_picker")
    object LinkedDevices     : Screen("linked_devices")
    object Weather           : Screen("weather")
    object Backup            : Screen("backup")
    object Inbox             : Screen("inbox")
    object UserSearch        : Screen("user_search")
    object AboutUs           : Screen("about_us")
    object TermsConditions   : Screen("terms_conditions")
    object PrivacyPolicy     : Screen("privacy_policy")
    object ContactUs         : Screen("contact_us")
}
